"""Alembic environment for cashU.

Runs either inside the app (``cashu.core.migrations.upgrade_to_head`` passes a
live connection in ``config.attributes["connection"]``) or from the ``alembic``
CLI in a source checkout, where it uses the app's own engine (CASHU_DATABASE_URL
or the data dir). From the CLI, ``upgrade``/``downgrade`` first take the same
backup the app takes (``backups/`` next to the database; the legacy repo DB's copy
goes to the data dir); ``alembic -x no-backup=1 ...`` skips it explicitly.
Autogenerated changes render in batch mode: SQLite cannot ALTER most things in
place, so Alembic rebuilds the table (copy, drop, rename).
"""

from __future__ import annotations

from logging.config import fileConfig

from alembic import context
from sqlmodel import SQLModel

from cashu import models  # noqa: F401  (registers tables on SQLModel.metadata)

config = context.config
target_metadata = SQLModel.metadata

if config.config_file_name is not None and "connection" not in config.attributes:
    fileConfig(config.config_file_name, disable_existing_loggers=False)


def _configure(**kwargs) -> None:
    context.configure(
        target_metadata=target_metadata,
        render_as_batch=True,
        compare_type=True,
        **kwargs,
    )


def _run(connection) -> None:
    _configure(connection=connection)
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_offline() -> None:
    from cashu.config import settings
    from cashu.db import resolve_database_url

    _configure(
        url=resolve_database_url(settings.database_url),
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def _cli_command() -> str | None:
    """Name of the alembic CLI command being run (``upgrade``, ``current``, ...)."""
    cmd = getattr(getattr(config, "cmd_opts", None), "cmd", None)
    fn = cmd[0] if isinstance(cmd, tuple) and cmd else None
    return getattr(fn, "__name__", None)


def _skip_backup() -> bool:
    value = context.get_x_argument(as_dictionary=True).get("no-backup", "")
    return value.strip().lower() in {"1", "true", "yes"}


def run_migrations_online() -> None:
    connection = config.attributes.get("connection")
    if connection is not None:
        _run(connection)
        return
    from cashu.core.migrations import backup_for_cli, migration_connection
    from cashu.db import engine

    copy = backup_for_cli(engine, _cli_command(), skip=_skip_backup())
    if copy is not None:
        print(f"Backed up the database to {copy}")
    with migration_connection(engine) as conn:
        _run(conn)


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
