"""Alembic environment for finanse.

Runs either inside the app (``finanse.core.migrations.upgrade_to_head`` passes a
live connection in ``config.attributes["connection"]``) or from the ``alembic``
CLI in a source checkout, where it uses the app's own engine (FINANSE_DATABASE_URL
or the data dir). Autogenerated changes render in batch mode: SQLite cannot
ALTER most things in place, so Alembic rebuilds the table (copy, drop, rename).
"""

from __future__ import annotations

from logging.config import fileConfig

from alembic import context
from sqlmodel import SQLModel

from finanse import models  # noqa: F401  (registers tables on SQLModel.metadata)

config = context.config
target_metadata = SQLModel.metadata

if config.config_file_name is not None and "connection" not in config.attributes:
    fileConfig(config.config_file_name, disable_existing_loggers=False)


def _configure(**kwargs) -> None:
    context.configure(
        target_metadata=target_metadata,
        render_as_batch=True,
        compare_type=True,
        **kwargs,
    )


def _run(connection) -> None:
    _configure(connection=connection)
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_offline() -> None:
    from finanse.config import settings
    from finanse.db import resolve_database_url

    _configure(
        url=resolve_database_url(settings.database_url),
        literal_binds=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    connection = config.attributes.get("connection")
    if connection is not None:
        _run(connection)
        return
    from finanse.core.migrations import migration_connection
    from finanse.db import engine

    with migration_connection(engine) as conn:
        _run(conn)


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
